/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package invoicing;

/**
 *
 * @author Ice
 */

import java.awt.BorderLayout;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    private InvoiceDisplayPanel invoiceDisplayPanel;
    private JButton proceedButton;
    private JButton generateButton;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        postInitComponents();
    }
private void postInitComponents() {
        // Set the main layout for the JFrame
        this.setLayout(new BorderLayout());

        // Create the panel to display the PDF
        invoiceDisplayPanel = new InvoiceDisplayPanel();
        this.add(invoiceDisplayPanel, BorderLayout.CENTER);

        // Create a bottom panel for buttons
        JPanel buttonPanel = new JPanel(); // FlowLayout by default

        // Create and add the "Generate Invoice" button
        generateButton = new JButton("Generate Invoice");
        generateButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        buttonPanel.add(generateButton);
        
        // Create and add the "Proceed" button, initially disabled
        proceedButton = new JButton("Proceed");
        proceedButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        proceedButton.setEnabled(false);
        buttonPanel.add(proceedButton);
        
        // Add the button panel to the bottom of the frame
        this.add(buttonPanel, BorderLayout.SOUTH);

        // Add action listeners
        generateButton.addActionListener(evt -> generateInvoiceAction());
        proceedButton.addActionListener(evt -> proceedAction());
        
        // Adjust frame size
        this.setSize(800, 900);
        setLocationRelativeTo(null);
    }
    
    private void generateInvoiceAction() {
        try {
            // 1. Generate the PDF and get its file path
            String filePath = InvoiceGenerator.createPdfInvoice();
            
            // 2. Load the generated PDF into the display panel
            invoiceDisplayPanel.loadPdf(filePath);
            
            // 3. Enable the proceed button
            proceedButton.setEnabled(true);
            
            JOptionPane.showMessageDialog(this,
                    "Invoice generated and displayed successfully.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error creating or displaying PDF: " + ex.getMessage(),
                    "Generation Failed",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void proceedAction() {
        // Create and show the payment frame
        new PaymentFrame().setVisible(true);
        // Close the current invoice frame
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}