/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.formdev.flatlaf.FlatDarkLaf;

/**
 *
 * @author USER
 */
public class paymentInformation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(paymentInformation.class.getName());

    /**
     * Creates new form paymentInformation
     */
    public paymentInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelZip = new javax.swing.JLabel();
        infoExpiration = new javax.swing.JTextField();
        labelCity = new javax.swing.JLabel();
        infoNumber = new javax.swing.JTextField();
        labelNumber = new javax.swing.JLabel();
        labelSecCode = new javax.swing.JLabel();
        infoZIP = new javax.swing.JTextField();
        infoName = new javax.swing.JTextField();
        infoSecCode = new javax.swing.JTextField();
        infoCity = new javax.swing.JTextField();
        labelStreet = new javax.swing.JLabel();
        labelExpiration = new javax.swing.JLabel();
        infoStreet = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();
        infoState = new javax.swing.JTextField();
        labelZip1 = new javax.swing.JLabel();
        infoZIP1 = new javax.swing.JTextField();
        labelTitle = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(590, 515));
        setResizable(false);

        labelName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelName.setText("Cardholder's Name");
        labelName.setPreferredSize(new java.awt.Dimension(64, 25));

        labelZip.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelZip.setText("ZIP/Postal Code");
        labelZip.setPreferredSize(new java.awt.Dimension(64, 25));

        infoExpiration.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoExpiration.setMaximumSize(new java.awt.Dimension(100, 24));
        infoExpiration.setPreferredSize(new java.awt.Dimension(64, 25));

        labelCity.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelCity.setText("City");
        labelCity.setPreferredSize(new java.awt.Dimension(64, 25));

        infoNumber.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoNumber.setMaximumSize(new java.awt.Dimension(100, 24));
        infoNumber.setPreferredSize(new java.awt.Dimension(64, 25));

        labelNumber.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelNumber.setText("Card Number");
        labelNumber.setPreferredSize(new java.awt.Dimension(64, 25));

        labelSecCode.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelSecCode.setText("Security Code");
        labelSecCode.setPreferredSize(new java.awt.Dimension(64, 25));

        infoZIP.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoZIP.setMaximumSize(new java.awt.Dimension(100, 24));
        infoZIP.setPreferredSize(new java.awt.Dimension(64, 25));
        infoZIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoZIPActionPerformed(evt);
            }
        });

        infoName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoName.setMaximumSize(new java.awt.Dimension(100, 24));
        infoName.setPreferredSize(new java.awt.Dimension(64, 25));

        infoSecCode.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoSecCode.setMaximumSize(new java.awt.Dimension(100, 24));
        infoSecCode.setPreferredSize(new java.awt.Dimension(64, 25));
        infoSecCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSecCodeActionPerformed(evt);
            }
        });

        infoCity.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoCity.setMaximumSize(new java.awt.Dimension(100, 24));
        infoCity.setPreferredSize(new java.awt.Dimension(64, 25));
        infoCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoCityActionPerformed(evt);
            }
        });

        labelStreet.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelStreet.setText("Street Address");
        labelStreet.setPreferredSize(new java.awt.Dimension(64, 25));

        labelExpiration.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelExpiration.setText("Expiration Date");
        labelExpiration.setPreferredSize(new java.awt.Dimension(64, 25));

        infoStreet.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoStreet.setMaximumSize(new java.awt.Dimension(100, 24));
        infoStreet.setPreferredSize(new java.awt.Dimension(64, 25));
        infoStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoStreetActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/logo.png"))); // NOI18N

        labelState.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelState.setText("State/Province");
        labelState.setPreferredSize(new java.awt.Dimension(64, 25));

        infoState.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoState.setMaximumSize(new java.awt.Dimension(100, 24));
        infoState.setPreferredSize(new java.awt.Dimension(64, 25));
        infoState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoStateActionPerformed(evt);
            }
        });

        labelZip1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelZip1.setText("Country");
        labelZip1.setPreferredSize(new java.awt.Dimension(64, 25));

        infoZIP1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        infoZIP1.setMaximumSize(new java.awt.Dimension(100, 24));
        infoZIP1.setPreferredSize(new java.awt.Dimension(64, 25));
        infoZIP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoZIP1ActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        labelTitle.setText("PAYMENT INFORMATION");

        btnRegister.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        btnRegister.setText("Register Account");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jButton1.setText("Back to Personal Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(90, 90, 90)
                .addComponent(labelTitle)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelSecCode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoExpiration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoSecCode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoState, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoZIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoZIP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(88, 88, 88)
                        .addComponent(btnRegister)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(labelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExpiration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSecCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelZip1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoSecCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoZIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoSecCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoSecCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoSecCodeActionPerformed

    private void infoStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoStateActionPerformed

    private void infoStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoStreetActionPerformed

    private void infoCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoCityActionPerformed

    private void infoZIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoZIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoZIPActionPerformed

    private void infoZIP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoZIP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoZIP1ActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        FlatDarkLaf.setup();
        new registration().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new paymentInformation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField infoCity;
    private javax.swing.JTextField infoExpiration;
    private javax.swing.JTextField infoName;
    private javax.swing.JTextField infoNumber;
    private javax.swing.JTextField infoSecCode;
    private javax.swing.JTextField infoState;
    private javax.swing.JTextField infoStreet;
    private javax.swing.JTextField infoZIP;
    private javax.swing.JTextField infoZIP1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelExpiration;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNumber;
    private javax.swing.JLabel labelSecCode;
    private javax.swing.JLabel labelState;
    private javax.swing.JLabel labelStreet;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelZip;
    private javax.swing.JLabel labelZip1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
